apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sunspec-gateway
resources:
- ns.yaml
- pvc.yaml
- svcacct.yaml
- deployment.yaml

secretGenerator:
- files:
  - config.yaml
  name: sunspec-gateway-config
