apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sunspec-gateway
resources:
- ns.yaml
- pvc.yaml
- svcacct.yaml
- deployment.yaml
- podmonitor.yaml

images:
- name: IMAGE:TAG
  newName: docker.io/petergrace/sunspec_gateway
  newTag: v0.5.1

secretGenerator:
- files:
  - config.yaml
  name: sunspec-gateway-config
