apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sunspec-gateway-state-db
  namespace: sunspec-gateway
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
