mqtt_server_addr= "10.174.2.40"
mqtt_server_port = 1883
mqtt_username = "pwrcell_rs"
mqtt_password = "pwrcell_rs"

#region points

##region Generac Inverter (102)
[[models.102]]
point = "PhVphA"
interval = "15"
device_class = "voltage"
state_class = "measurement"
precision = 1
[[models.102]]
point = "PhVphB"
interval = "15"
device_class = "voltage"
state_class = "measurement"
precision = 1
#endregion


[[models.802]]
point = "ChaSt"
interval = 60
#homeassistant = false

[[models.804]]
point = "St"
interval = 10
#homeassistant = false

[[models.804]]
point = "ConFail"
interval = 60
#homeassistant = false

[[models.804]]
point = "Evt1"
interval = 60
#homeassistant = false


[[models.802]]
point = "State"
interval = 60
#homeassistant = false

[[models.802]]
point = "Evt1"
interval = 60
#homeassistant = false

[[models.802]]
point = "CellVMin"
interval = 60
device_class = "voltage"
state_class = "measurement"
precision = 1

[[models.802]]
point = "CellVMax"
interval = 60
device_class = "voltage"
state_class = "measurement"
precision = 1

[[models.802]]
point = "CellVAvg"
interval = 60
device_class = "voltage"
state_class = "measurement"
precision = 1

[[models.802]]
point = "W"
interval = 60
device_class = "power"
state_class = "measurement"
precision = 1

[[models.802]]
point = "SoC"
interval = 60
precision = 2


[[models.64208]]
point = "SysMd"
interval = 60
#homeassistant = false

[[models.64208]]
point = "ErrorWord"
interval = 60
#homeassistant = false

[[models.64204]]
point = "Px1"
interval = 15
device_class = "power"
state_class = "measurement"
precision = 1

[[models.64204]]
point = "Px2"
interval = 15
device_class = "power"
state_class = "measurement"
precision = 1

[[models.64204]]
point = "Whx"
interval = 15
device_class = "energy"
precision = 1

[[models.64204]]
point = "Whin"
interval = 15
device_class = "energy"
precision = 1


#region Generac REbus Status (64207)
[[models.64207]]
point = "St"
interval = "15"

[[models.64207]]
point = "P"
interval = "15"

[[models.64207]]
point = "E"
interval = "60"
device_class = "energy"

[[models.64207]]
point = "I"
interval = "15"

[[models.64207]]
point = "V"
interval = "15"
[[models.64207]]
point = "T"
interval = "30"
device_class = "temperature"
state_class = "measurement"
precision = 2
uom = "°C"

[[models.64207]]
point = "Ev"
interval = "60"
#homeassistant = false

[[models.64207]]
point = "RB"
interval = "60"
#homeassistant = false

#endregion
#endregion

#region units
[[unit]]
addr = "127.0.0.1:5083"
slave_id = "1"

[[unit]]
addr = "127.0.0.1:5083"
slave_id = "3"

[[unit]]
addr = "127.0.0.1:5083"
slave_id = "4"
#[[unit]]
#addr = "127.0.0.1:5083"
#slave_id = "5"
#[[unit]]
#addr = "127.0.0.1:5083"
#slave_id = "6"

#[[unit]]
#addr = "127.0.0.1:5083"
#slave_id = "8"
#
#[[unit]]
#addr = "127.0.0.1:5083"
#slave_id = "9"
#
#[[unit]]
#addr = "127.0.0.1:5083"
#slave_id = "10"
#
#[[unit]]
#addr = "127.0.0.1:5083"
#slave_id = "11"
#endregion
